### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by zhuminjie** [ddemidov/amgcl_benchmarks#2]
Hi,

Thank you a lot for implementing this wonderful library. I really want to use it. The problem I have now is the benchmark file amgcl.cu in the shared memory for poisson equation. I have the K20m GPU installed and can compile this file. But When I run it, it gives,

terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA error 2 at "./amgcl/amgcl/backend/cuda.hpp:247
Abort (core dumped)

I didn't try anything in the source code but compile it with make

I really need your help to find anything I did wrong! Thank you so much!

Here is my makefile

CUDA_VERSION = 6.5.14
LINKFLAGS = -Xcompiler \"-Wl,-rpath,/usr/local/apps/cuda/cuda-$(CUDA_VERSION)/lib64\"
LIBS = -L/usr/local/apps/cuda/cuda-$(CUDA_VERSION)/lib64 -lcudart -lcusparse

poisson_cu.o: poisson.cu
	$(NVCC) -std=c++11 -O2 $(INCLUDES) $(CUDA_INC) poisson.cu -c -o poisson_cu.o

poisson_cu: poisson_cu.o
	$(NVCC) $(LINKFLAGS)  $(LIBS) poisson_cu.o -o poisson_cu

**Comment by ddemidov** [comment]
What is the output of `nvidia-smi` (you need to run it from command line)?

**Comment by ddemidov** [comment]
Looks like `error 2` is an 'out of memory error'. Try to reduce the problem size. Also, if the K20 is not the only Nvidia GPU on the machine, make sure you are using the correct one.

**Comment by zhuminjie** [comment]
Thank you for the reply. The k20 is actually installed. I change cuda version to 10.0 and with -O3, it can run successfully. Not sure why, it seems working now!

Another question is that have you compared with Amgx from Nvidia ?

https://github.com/NVIDIA/AMGX

**Comment by ddemidov** [comment]
> Another question is that have you compared with Amgx from Nvidia ?

Not really. If you manage to run the same tests though, please feel free to post the results here (or make a pull request with the testing code).

**Comment by zhuminjie** [comment]
Sure, if I can run it, I will let you know.
