### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by syaskovets** [ddemidov/amgcl_benchmarks#4]
Hi,
I am currently involved in an open-source project for particle simulations (https://www.sciencedirect.com/science/article/pii/S0010465519300852?via%3Dihub), and working on comparing backends for solving sparse linear systems of equations (Poisson problem). I have found your repository particularly handy, thank you. Unfortunately, the examples utilizing amgcl (I have started with shared memory), seem to be not compiling right with the latest version of amgcl. The errors are showing up when instantiating and applying solver, e.g.

`type/value mismatch at argument 2 in template parameter list for ‘template<class Precond, class IterativeSolver> class amgcl::mpi::make_solver’`

Could you please clarify whether the examples are compiling right at your side? If so, I will be looking for different possible reasons of the errors. If this is not the case, and some interfaces of the framework have changed, could you please update the examples? Though I am working on it myself, it would save me some time.
Thanks in advance!

**Comment by ddemidov** [comment]
I have updated the code so that it compiles with the latest amgcl. Keep in mind that the CUSP library tests no longer compile with the current CUDA (I think CUSP requires CUDA 9 to work).

**Comment by syaskovets** [comment]
Thank you very much, the code compiles with my amgcl setup as well. Also, noticed about the CUSP, thanks. Closing the issue.
